#!/usr/bin/julia

currTriNum = 1
currNatNum = 1

function numFactors(x)
    if (x > 1)
        return prod(collect(values(factor(x))) .+ 1) #The product of the values of the array generated by taking the values from the ValueIterator that iterates over the values in the dictionary describing the prime factors of a number and adding one to each one.
    else
        return 1 #x must equal 1 here, since that's where we start, and the previous line creates an error when using one, because it doesn't have a prime factorization
    end
end

while (numFactors(currTriNum) <= 500)
    currNatNum += 1
    currTriNum += currNatNum
end

println(currTriNum)
